apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-config
policyDefaults:
  namespace: policies
  placement:
    labelSelector:
      datacenter: detroit
policies:
- name: kubecon-demo-configmap
  manifests:
    - path: input/namespace.yaml
  remediationAction: enforce
